//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMETA.SentimentAnalysisPlatform.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordSentiment
    {
        public int WordId { get; set; }
        public string Word { get; set; }
        public Nullable<int> Positive { get; set; }
        public Nullable<int> Negative { get; set; }
        public Nullable<int> Anger { get; set; }
        public Nullable<int> Anticipation { get; set; }
        public Nullable<int> Disgust { get; set; }
        public Nullable<int> Fear { get; set; }
        public Nullable<int> Joy { get; set; }
        public Nullable<int> Sadness { get; set; }
        public Nullable<int> Surprise { get; set; }
        public Nullable<int> Trust { get; set; }
    }
}
